### ISSUE TITLE
Including dependencies in Pypi package

### ISSUE THREAD

**Issue by manulera** [hiyama341/teemi#16]
Hello! When installing the package from Pypi, it does not install any necessary dependency. The user has to separately install pandas, Biopython, etc (which may lead to them using incompatible versions). For now I am using requirements.txt, but it would be good to include them in the next pypi release.

**Comment by hiyama341** [comment]
Hi Manu, 

Thanks a lot for raising this issue. I think I have fixed it by basically just using the requirements file for easier management by including the following in the setup.py file: 

`requirements = []
with open('requirements.txt', 'r') as fh:
    for line in fh:
        requirements.append(line.strip())
        `

And in the setup() function : 

`    install_requires = requirements,
`

I will add this to the new release :) 

Thanks again and have a nice day!
